# Generated by Django 5.2.9 on 2025-12-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_name', models.CharField(max_length=40)),
                ('Emp_email', models.EmailField(max_length=254)),
                ('Emp_username', models.CharField(max_length=100)),
                ('Emp_password', models.CharField(max_length=128)),
            ],
        ),
    ]
